version = 0.1

[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::637423558612:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-5SPgDeNUlrwA"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::637423558612:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-fNpqvMKVUbvh"
cloudformation_execution_role = "arn:aws:iam::637423558612:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-W66707tApuDS"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-af97qdi8wfim"
image_repository = "637423558612.dkr.ecr.us-west-2.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-9lhbvaukc4fg"
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::637423558612:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-igNnzKTfKRzP"
cloudformation_execution_role = "arn:aws:iam::637423558612:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-nioRjYdTmjbE"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-wlm7vndz4iqy"
image_repository = "637423558612.dkr.ecr.us-west-2.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-6a0plfyuigty"
region = "us-west-2"
